Repository nbc-react-final-project-eightball/fancyplace-project, pull requests merged in 2024-02, with the labels that each got.

#111 Feature/cart 장바구니 코드 리팩토링
  package.json
  src/App.tsx
  src/Type/TypeInterface.tsx
  src/components/Cart/CartListInfo.tsx
  src/components/Cart/PaymentInfo.tsx
  src/components/Cart/ProgressIndicator.tsx
  src/components/payment/TossApi.tsx
  src/hooks/useCartList.tsx
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
  src/redux/configStore.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledPayment/StPaymentPage.ts
  src/styledComponent/styledPayment/stPayment.ts
  yarn.lock
Labels: 🩹 fix, ♻️ refactor, ➕add

#117 design: 장바구니, 최근 본 상품 반응형 등 전체 수정(#101)
  src/GlobaStyle.js
  src/components/Main/MainBttomAlbum.tsx
  src/components/ProfileCard.tsx
  src/components/layout/Header.tsx
  src/components/mypage/RecentProducts.tsx
  src/components/payment/TossApi.tsx
  src/page/Mypage.tsx
  src/page/PaymentPage.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMain/StMainCarousel.ts
  src/styledComponent/styledMain/StMainTopCarousel.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  src/styledComponent/styledMypage/StMypageLayout.ts
  src/styledComponent/styledMypage/StRecentProducts.ts
  src/styledComponent/styledPayment/stPayment.ts
Labels: 💄design

#120 장바구니 빈 페이치 추가 + 오류수정
  src/components/Cart/CartEmpty.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/hooks/useCartList.tsx
  src/page/Cartpage.tsx
Labels: 🩹 fix, ➕add

#121 상품 디테일 이미지 크기 수정
  package.json
  src/GlobaStyle.js
  src/components/Detail/Product.tsx
  src/components/Detail/ProductInfo.tsx
  src/components/layout/DarkMode.tsx
  src/components/layout/ScrollToTop.tsx
  src/components/layout/SideBar.tsx
  src/components/mypage/RecentProducts.tsx
  src/page/GoodsList.tsx
  src/page/Mainpage.tsx
  src/redux/modules/GoodsList/GoodsListSlice.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  yarn.lock
Labels: 🍻 test

#124 [update/goods-style] del : 개발중인 부분 코드 숨김 처리
  public/img/common/checked.svg
  src/components/Chat/ChatDetail.tsx
  src/components/layout/Header.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledLayout/StHeader.tsx
Labels: 🔥 del

#125 토스api 커스텀 훅으로 변경
  src/components/Cart/CartListInfo.tsx
  src/components/Cart/PaymentInfo.tsx
  src/components/payment/Address.tsx
  src/components/payment/TossApi.tsx
  src/hooks/useAuth.ts
  src/hooks/useCartList.tsx
  src/hooks/useTossApi.tsx
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
Labels: 🩹 fix, ♻️ refactor

#127 fix : 소셜 로그인 훅 코드 수정, 깃허브로 로그인하고 새로고침 시 displayName 표시
  src/components/auth/AuthForm.tsx
  src/hooks/useAuth.ts
  src/hooks/useSocialLogin.ts
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 🐛 fix

#128 토스api 오류수정 , props이름 수정 #112
  src/components/Cart/OrderListInfo.tsx
  src/components/Cart/PaymentInfo.tsx
  src/components/payment/TossApi.tsx
  src/hooks/useCartList.tsx
  src/hooks/useTossApi.tsx
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
  src/styledComponent/styledPayment/stPayment.ts
Labels: 🩹 fix, ♻️ refactor

#130 [feature/dtail1] 이미지 수정 및 css 버그 수정 #129
  public/img/ProductCardImg/aespa1.webp
  public/img/ProductCardImg/aespa2.webp
  public/img/ProductCardImg/blackpink1.webp
  public/img/ProductCardImg/blackpink2.webp
  public/img/ProductCardImg/bts1.webp
  public/img/ProductCardImg/bts2.webp
  public/img/ProductCardImg/exo3.webp
  public/img/ProductCardImg/idle1.webp
  public/img/ProductCardImg/itzy1.webp
  public/img/ProductCardImg/ive1.webp
  public/img/ProductCardImg/ive2.webp
  public/img/ProductCardImg/izone1.webp
  public/img/ProductCardImg/kanna1.webp
  public/img/ProductCardImg/lesserafim1.webp
  public/img/ProductCardImg/lesserafim2.webp
  public/img/ProductCardImg/lesserafim3.webp
  public/img/ProductCardImg/lesserafim4.webp
  public/img/ProductCardImg/lesserafim5.webp
  public/img/ProductCardImg/monstax1.webp
  public/img/ProductCardImg/nct1.webp
  public/img/ProductCardImg/nct2.webp
  public/img/ProductCardImg/nct3.webp
  public/img/ProductCardImg/newjeans1.webp
  public/img/ProductCardImg/newjeans2.webp
  public/img/ProductCardImg/redvelvet1.webp
  public/img/ProductCardImg/redvelvet2.webp
  public/img/ProductCardImg/riize1.webp
  public/img/ProductCardImg/riize2.webp
  public/img/ProductCardImg/riize3.webp
  public/img/ProductCardImg/seventeen1.webp
  public/img/ProductCardImg/seventeen2.webp
  public/img/ProductCardImg/seventeen3.webp
  public/img/ProductCardImg/shinee1.webp
  public/img/ProductCardImg/shinee2.webp
  public/img/ProductCardImg/shinee3.webp
  public/img/ProductCardImg/shinee6.webp
  public/img/ProductCardImg/shinee7.webp
  public/img/ProductCardImg/stayc1.webp
  public/img/ProductCardImg/straykids1.webp
  public/img/ProductCardImg/straykids2.webp
  public/img/ProductCardImg/straykids3.webp
  public/img/ProductCardImg/straykids4.webp
  public/img/ProductCardImg/theboyz1.webp
  public/img/ProductCardImg/twice1.webp
  public/img/ProductCardImg/twice2.webp
  public/img/ProductCardImg/twice3.webp
  public/img/ProductCardImg/twice4.webp
  public/img/ProductCardImg/twice5.webp
  public/img/ProductCardImg/txt1.webp
  public/img/ProductCardImg/txt2.webp
  src/components/Detail/ProductInfo.tsx
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainBttomAlbum.tsx
  src/page/GoodsList.tsx
  src/page/Mypage.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledMypage/StMypage.tsx
Labels: 🐛 fix

#135 반응형 추가
  src/components/layout/Header.tsx
  src/page/SearchList.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledMain/StMainCarousel.ts
Labels: 🩹 fix

#142 [feature/wishlist] add,feat : 위시리스트 기능 추가
  src/components/Detail/ProductInfo.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/Wishlist.tsx
  src/page/WishListPage.tsx
  src/styledComponent/styledMypage/StWishlist.tsx
Labels: 🎉 feat, ➕add

#141 장바구니 삭제 / 원하는 항목만 결제페이지이동
  src/App.tsx
  src/Type/TypeInterface.tsx
  src/components/Cart/OrderListInfo.tsx
  src/hooks/useCartList.tsx
  src/hooks/useTossApi.tsx
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
  src/page/PaymentSuccess.tsx
  src/redux/configStore.tsx
  src/redux/modules/orderList/orderListSlice.ts
  src/shared/Router.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledPayment/stPayment.ts
Labels: 🎉 feat, 🔥 del, 🩹 fix, 🚚 edit, ♻️ refactor, 📝 docs, ➕add

#140 에러 수정
  public/img/ProductDetail/redvelvet1_1.webp
  public/img/ProductDetail/stayc3_1.webp
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/Wishlist.tsx
  src/page/GoodsList.tsx
  src/redux/modules/GoodsList/GoodsListSlice.tsx
  src/styledComponent/styledGoodsList/StGoodsList.tsx
Labels: 🩹 fix

#143 payment 발표전 머지
  package.json
  src/Type/TypeInterface.tsx
  src/hooks/useCartList.tsx
  src/hooks/useTossApi.tsx
  src/page/Cartpage.tsx
  src/page/Mypage.tsx
  src/page/OrderListPage.tsx
  src/page/PaymentPage.tsx
  src/page/PaymentSuccess.tsx
  src/redux/configStore.tsx
  src/redux/modules/Cart/cartSlice.ts
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  yarn.lock
Labels: 🔥 del

#146 [update/goods-style] 검색창, 리뷰, 장바구니 삭제 버튼 등 디자인 수정
  src/components/Detail/Product.tsx
  src/components/Detail/StarRate.tsx
  src/components/mypage/Wishlist.tsx
  src/page/SearchList.tsx
  src/shared/Router.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledGoodsList/StGoodsList.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledMain/StMainCarousel.ts
  src/styledComponent/styledMypage/StWishlist.tsx
  src/styledComponent/styledPayment/stPaymentSuccess.ts
Labels: 💄design, ➕add
