Repository nbc-react-final-project-eightball/fancyplace-project, pull requests merged in 2024-01, with the labels that each got.

#10 [feature/layout]레이아웃 기본 세팅 #9
  src/component/layout/Footer.tsx
  src/component/layout/Header.tsx
  src/component/layout/SideBar.tsx
  src/page/Layout.tsx
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 🎉 feat, 💄 style

#15 Feature/main page
  package.json
  public/img/Album1.jpg
  public/img/Album2.jpg
  public/img/Album3.jpg
  public/img/Album4.jpg
  public/img/Album5.jpg
  public/img/Album6.png
  public/img/Album7.jpg
  public/img/Album8.jpg
  public/img/L.png
  public/img/P1.jpg
  public/img/P2.jpg
  public/img/P3.jpg
  public/img/P4.jpg
  public/img/P5.jpg
  public/img/P6.jpg
  public/img/P7.jpg
  public/img/P8.jpg
  public/img/R.png
  public/img/bg1.jpg
  src/component/layout/SideBar.tsx
  src/component/layout/a
  src/component/login/a
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainBttomAlbum.tsx
  src/components/ProductDetail/a
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideBar.tsx
  src/components/login/a
  src/page/Layout.tsx
  src/page/Mainpage.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  yarn.lock
Labels: 🐛 fix, 🚚 edit, 💄design, ➕add

#21 Feature/header
  src/components/layout/BasicHeader.tsx
  src/components/layout/ChangeHeader.tsx
  src/components/layout/Header.tsx
  src/styledComponent/styledHeader/StHeader.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 🔥 del, 🚚 edit, ♻️ refactor

#22 [Feature/login] 로그인 회원가입 기능 구현
  package.json
  src/API/a
  src/App.tsx
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/a
  src/components/ProfileCard.tsx
  src/components/auth/AuthForm.tsx
  src/components/layout/Header.tsx
  src/components/layout/a
  src/components/login/a
  src/contexts/AuthContext.js
  src/firebase/config.js
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useSocialLogin.ts
  src/page/Authpage.tsx
  src/page/Loginpage.tsx
  src/reducers/authReducer.ts
  src/shared/Router.tsx
  src/styledComponent/styledAuth/StAuth.ts
  src/styledComponent/styledAuth/StAuthForm.ts
  src/styledComponent/styledLogin/StLogin.tsx
  tsconfig.json
  yarn.lock
Labels: 🔥 del, 🚚 edit, 💄design, ➕add

#24 [update/readme ]Update README.md
  README.md
Labels: 📝 docs

#29 Feature/goods list 굿즈리스트 2중 카테고리 추가 및 스타일수정
  public/img/ProductCardImg/1000004652_main_0100.jpg
  public/img/ProductCardImg/1000004905_main_075.jpg
  public/img/ProductCardImg/1000004924_main_013.jpg
  public/img/ProductCardImg/1000004927_main_052.jpg
  public/img/ProductCardImg/Boa1.png
  public/img/ProductCardImg/ESPA.png
  public/img/ProductCardImg/YO1.jpg
  public/img/ProductCardImg/YO2.jpg
  public/img/ProductCardImg/아이즈원1.jpg
  public/img/ProductCardImg/아이즈원2.jpg
  public/img/ProductCardImg/있지1.jpg
  public/img/ProductCardImg/칸나1.jpg
  public/img/ProductCardImg/칸나2.jpg
  public/img/ProductCardImg/트와이스1.jpg
  public/img/ProductCardImg/트와이스2.jpg
  public/img/ProductCardImg/트와이스3.jpg
  public/img/new.svg
  public/img/pre.svg
  public/img/soldouticon.png
  src/components/layout/SideBar.tsx
  src/page/GoodsList.tsx
  src/page/Mainpage.tsx
  src/shared/Router.tsx
  src/styledComponent/styledGoodsList/StGoodsList.tsx
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 🚚 edit, 💄design, ➕add

#37 [feature/login] 로그인/회원가입 유효성 검사, 배송지 추가
  package.json
  public/img/logo/github.png
  public/img/logo/google.png
  src/App.tsx
  src/components/AddressModal.tsx
  src/components/ProfileCard.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/DeliveryAddress.tsx
  src/components/layout/Header.tsx
  src/contexts/AuthContext.js
  src/hooks/useAddressModal.tsx
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useSignUp.ts
  src/hooks/useSocialLogin.ts
  src/page/Authpage.tsx
  src/reducers/authReducer.ts
  src/redux/configStore.tsx
  src/redux/modules/modal/modalSlice.ts
  src/redux/modules/signup/signUpSlice.ts
  src/redux/modules/모듈 각폴더 만들고 써주세요
  src/shared/Router.tsx
  src/styledComponent/styledAddressModal/StAddressModal.ts
  src/styledComponent/styledAuth/StAuthForm.ts
  src/styledComponent/styledLayout/StHeader.tsx
  yarn.lock
Labels: 🐛 fix, 🚚 edit, ➕add

#40 [Feature/mypage] 마이페이지
  public/img/logo/logo.svg
  src/GlobaStyle.js
  src/components/ProfileCard.tsx
  src/components/Select/CustomSelect.tsx
  src/components/auth/AuthForm.tsx
  src/components/layout/Header.tsx
  src/index.css
  src/page/CouponPage.tsx
  src/page/Mypage.tsx
  src/page/OrderListPage.tsx
  src/page/ProfileSettingsPage.tsx
  src/page/ShippingPage.tsx
  src/page/WishListPage.tsx
  src/shared/Router.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  src/styledComponent/styledSelect/StSelect.tsx
Labels: 💄design, ➕add

#41 장바구니 -> 결제페이지로 넘어가기 #26
  package.json
  src/page/Cartpage.tsx
  src/page/Chat.tsx
  src/page/PaymentPage.tsx
  src/shared/Router.tsx
  yarn.lock
Labels: 🎉 feat, 💄design, ➕add

#45 [feature/mypage] 마이페이지 UI 구현
  package.json
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainTopCarousel.tsx
  src/components/ProfileCard.tsx
  src/components/Select/CustomSelect.tsx
  src/components/layout/Header.tsx
  src/page/ChatListPage.tsx
  src/page/Layout.tsx
  src/page/Mainpage.tsx
  src/page/Mypage.tsx
  src/shared/Router.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMain/StMainTopCarousel.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  yarn.lock
Labels: 🩹 fix, 💄design, ➕add

#46 Feature/payment test 결제사이클 돌려보기 !
  src/components/Detail/ProductInfo.tsx
  src/page/Cartpage.tsx
  src/page/GoodsList.tsx
  src/page/PaymentPage.tsx
  src/page/PaymentSuccess.tsx
  src/shared/Router.tsx
  src/styledComponent/styledCart/StCart.tsx
Labels: 💄design, 🍻 test, ➕add

#48 [feature/login] add : 로그인 상태 유지 구현
  src/App.tsx
  src/components/AddressModal.tsx
  src/components/ProfileCard.tsx
  src/components/Select/CustomSelect.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/hooks/useSocialLogin.ts
  src/page/Mypage.tsx
  src/redux/modules/signup/signUpSlice.ts
  src/styledComponent/styledLayout/StHeader.tsx
Labels: 🐛 fix, ➕add

#52 [update/payment-style] design : 결제 완료 페이지 UI 작업
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/page/ChatListPage.tsx
  src/page/CouponPage.tsx
  src/page/Mypage.tsx
  src/page/OrderListPage.tsx
  src/page/PaymentSuccess.tsx
  src/page/ProfileSettingsPage.tsx
  src/page/ShippingPage.tsx
  src/page/WishListPage.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  src/styledComponent/styledMypage/StMypageLayout.ts
  src/styledComponent/styledMypage/StProfileSettings.ts
  src/styledComponent/styledPayment/stPaymentSuccess.ts
Labels: 💄design

#54 장바구니 페이지 CSS변경
  public/img/common/checked.svg
  src/page/Cartpage.tsx
  src/shared/Router.tsx
  src/styledComponent/styledCart/StCart.tsx
Labels: 💄design, ✨style

#57 design: 전체적인 UI 등 수정
  src/hooks/useLogin.ts
  src/hooks/useSocialLogin.ts
  src/page/Cartpage.tsx
  src/page/Detail.tsx
  src/page/GoodsList.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledGoodsList/StGoodsList.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledPayment/stPaymentSuccess.ts
Labels: 💄design

#63 Feature/payment test
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledPayment/StPaymentPage.ts
Labels: 🎉 feat, 💄design, ✨style

#65 [feature/login] add : 회원가입 시 주소, 상세 주소 저장 수정
  package.json
  src/App.tsx
  src/components/AddressModal.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/DeliveryAddress.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/firebase/config.js
  src/hooks/useAuth.ts
  src/hooks/useLogin.ts
  src/hooks/useProfileUpdate.tsx
  src/hooks/useSignUp.ts
  src/hooks/useSocialLogin.ts
  src/page/Layout.tsx
  src/redux/modules/signup/signUpSlice.ts
  src/styledComponent/styledMypage/StProfileSettings.ts
  src/styledComponent/styledPayment/stPayment.ts
  yarn.lock
Labels: 🐛 fix, ➕add

#58 Feature/goods list 중간발표전
  public/img/L.png
  public/img/L.svg
  public/img/ProductCardImg/BTS2.jpg
  public/img/ProductCardImg/BTS3.jpg
  public/img/ProductCardImg/뉴진스1.jpg
  public/img/ProductCardImg/뉴진스2.jpg
  public/img/ProductCardImg/더보이즈1.jpg
  public/img/ProductCardImg/레드벨벳1.jpg
  public/img/ProductCardImg/르세라핌1.jpg
  public/img/ProductCardImg/몬스타엑스1.jpg
  public/img/ProductCardImg/세븐틴1.jpg
  public/img/ProductCardImg/세븐틴2.jpg
  public/img/ProductCardImg/세븐틴3.jpg
  public/img/ProductCardImg/스테이씨1.jpg
  public/img/ProductCardImg/스트레이키즈1..jpg
  public/img/ProductCardImg/스트레이키즈1.JPG
  public/img/ProductCardImg/스트레이키즈3.jpg
  public/img/ProductCardImg/아이브1.jpg
  public/img/ProductCardImg/엑소1.jpg
  public/img/ProductCardImg/엑소2.jpg
  public/img/ProductCardImg/여자아이들1.jpg
  public/img/ProductDetail/BTS2_1.jpg
  public/img/ProductDetail/BTS3_1.jpg
  public/img/ProductDetail/뉴진스1_1.jpg
  public/img/ProductDetail/뉴진스2_1.jpg
  public/img/ProductDetail/뉴진스2_2.jpg
  public/img/ProductDetail/더보이즈1.jpg
  public/img/ProductDetail/레드벨벳1_1.jpg
  public/img/ProductDetail/르세라핌1_1.jpg
  public/img/ProductDetail/몬스타엑스1_1.jpg
  public/img/ProductDetail/세븐틴1_1.jpg
  public/img/ProductDetail/세븐틴2_1.jpg
  public/img/ProductDetail/세븐틴3_1.jpg
  public/img/ProductDetail/스테이씨1_1.jpg
  public/img/ProductDetail/스트레이키즈3_1.jpg
  public/img/ProductDetail/아이브1_1.jpg
  public/img/ProductDetail/엑소1_1.jpg
  public/img/ProductDetail/엑소2_1.jpg
  public/img/ProductDetail/여자아이들1_1.jpg
  public/img/R.png
  public/img/R.svg
  public/img/sidebar.svg
  src/Type/TypeInterface.tsx
  src/components/Detail/Product.tsx
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainBttomAlbum.tsx
  src/components/Main/MainBttomAlbumSkeleton.tsx
  src/components/Main/MainBttomSkeleton.tsx
  src/components/Main/MainTopCarousel.tsx
  src/components/layout/SideBar.tsx
  src/page/Detail.tsx
  src/page/GoodsList.tsx
  src/page/Mainpage.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMain/MainBttomSkeleton.tsx
  src/styledComponent/styledMain/StMain.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMain/StMainTopCarousel.tsx
Labels: 💄design

#69 [Feature/layout-prepare] 준비중 페이지, 404 페이지 레이아웃 구현
  src/components/auth/DeliveryAddress.tsx
  src/components/layout/PrepareLayout.tsx
  src/components/layout/SideBar.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/hooks/usePasswordUpdate.tsx
  src/hooks/useProfileUpdate.tsx
  src/hooks/useSignUp.ts
  src/page/Announcements.tsx
  src/page/Artists.tsx
  src/page/ChatListPage.tsx
  src/page/CouponPage.tsx
  src/page/NotFound.tsx
  src/page/OrderListPage.tsx
  src/page/ProfileSettingsPage.tsx
  src/page/ShippingPage.tsx
  src/page/WishListPage.tsx
  src/redux/modules/signup/signUpSlice.ts
  src/shared/Router.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StPrepareLayout.tsx
  src/styledComponent/styledMypage/StProfileSettings.ts
Labels: 🎉 feat, 💄design, ➕add

#70 [Feature/profileSettings] 정보 수정 페이지 구현
  src/components/AddressModal.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/hooks/useProfileUpdate.tsx
  src/styledComponent/styledMypage/StMypageLayout.ts
  src/styledComponent/styledMypage/StProfileSettings.ts
Labels: 🎉 feat, 💄design, ➕add

#72 레이아웃 /메인페이지 / 디테일 페이지 / 굿즈리스트 반응형 css 추가 768px&480px
  src/components/Detail/Product.tsx
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainBttomAlbum.tsx
  src/components/Main/MainBttomSkeleton.tsx
  src/components/Main/MainTopCarousel.tsx
  src/components/layout/SideBar.tsx
  src/page/Detail.tsx
  src/page/GoodsList.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledGoodsList/StGoodsList.tsx
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledMain/MainBttomSkeleton.tsx
  src/styledComponent/styledMain/StMain.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMain/StMainTopCarousel.tsx
Labels: 💄design

#78 [Feature/profileSettings] 정보 수정 페이지 반응형 디자인, 안내 문구 추가
  src/components/auth/AuthForm.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/page/ProfileSettingsPage.tsx
  src/styledComponent/styledAddressModal/StAddressModal.ts
  src/styledComponent/styledAuth/StAuth.ts
  src/styledComponent/styledAuth/StAuthForm.ts
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StPrepareLayout.tsx
  src/styledComponent/styledMypage/StMypage.tsx
  src/styledComponent/styledMypage/StMypageLayout.ts
  src/styledComponent/styledMypage/StProfileSettings.ts
  src/styledComponent/styledPayment/StPaymentPage.ts
Labels: 💄design, ➕add

#81 장바구니 반응형 780px,480px #64
  src/page/Cartpage.tsx
  src/page/PaymentPage.tsx
  src/styledComponent/styledCart/StCart.tsx
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 💄design, ✨style

#84 [feature/goodsLIst] 반응형에서 가로스크롤 생기는 문제 추가수정 #71
  src/GlobaStyle.js
  src/components/Main/MainBottomCarousel.tsx
  src/components/layout/Footer.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
Labels: 🔨chore, 💄design

#83 결제하기 버튼 부분만 임시변경
  src/page/PaymentPage.tsx
  src/styledComponent/styledLayout/StLayout.tsx
Labels: 💄design, ✨style

#90 [feature/shipping] 배송지 관리 기능 구현 및 반응형, 푸터 수정
  src/GlobaStyle.js
  src/components/AddressModal.tsx
  src/components/auth/DeliveryAddress.tsx
  src/components/layout/Footer.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/layout/SideBar.tsx
  src/components/mypage/ProfileSettingsForm.tsx
  src/components/mypage/ShippingRegisterModal.tsx
  src/hooks/useAddressModal.tsx
  src/hooks/useGetAddresses.ts
  src/hooks/useModal.tsx
  src/hooks/useSetAddresses.ts
  src/page/ShippingPage.tsx
  src/redux/configStore.tsx
  src/redux/modules/modal/modalSlice.ts
  src/redux/modules/shipping/shippingSlice.ts
  src/redux/modules/signup/signUpSlice.ts
  src/styledComponent/styledAddressModal/StAddressModal.ts
  src/styledComponent/styledAuth/StAuthForm.ts
  src/styledComponent/styledLayout/StHeader.tsx
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledLayout/StPrepareLayout.tsx
  src/styledComponent/styledLayout/StSidebar.tsx
  src/styledComponent/styledMypage/StShipping.ts
  src/styledComponent/styledMypage/StShippingModal.ts
  src/styledComponent/styledSelect/StSelect.tsx
Labels: 🎉 feat, 🚚 edit, 💄design, ➕add

#93 [feature/goodsList] 메인 캐러셀 크기별 반응형 #92
  src/components/Main/MainBottomCarousel.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMain/StMainTopCarousel.tsx
Labels: 🐛 fix, 💄design

#94 [feature/goodsList] 자잘한 추가수정 #92
  src/components/Main/MainBottomCarousel.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
Labels: 🩹 fix, 💄design

#96 480px 반응형 수정 #82
  src/styledComponent/styledCart/StCart.tsx
Labels: 💄design, ✨style

#100 [feature/login] design : 반응형 인풋 넘치는 부분 수정 작업
  src/hooks/useLogout.ts
  src/styledComponent/styledAuth/StAuthForm.ts
  src/styledComponent/styledLayout/StLayout.tsx
  src/styledComponent/styledMain/MainBttomSkeleton.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMypage/StProfileSettings.ts
  src/styledComponent/styledMypage/StShippingModal.ts
Labels: 💄design

#106 [update/goods-style]
  public/img/ProductCardImg/bts1.jpg
  public/img/ProductCardImg/bts2.jpg
  public/img/ProductCardImg/izone1.jpg
  public/img/ProductCardImg/kanna1.jpg
  public/img/ProductCardImg/lesserafim1.jpg
  public/img/ProductCardImg/lesserafim4.jpg
  public/img/ProductCardImg/newjeans1.jpg
  public/img/ProductCardImg/newjeans2.jpg
  public/img/ProductCardImg/riize1.jpg
  public/img/ProductCardImg/riize2.jpg
  public/img/ProductCardImg/riize3.jpg
  public/img/ProductCardImg/seventeen1.jpg
  public/img/ProductCardImg/seventeen2.jpg
  src/Type/TypeInterface.tsx
  src/page/GoodsList.tsx
Labels: 🚚 edit, 💄design

#107 Feature/detail1
  src/components/Detail/Product.tsx
  src/components/Detail/ProductRecentItems.tsx
  src/components/Detail/StarRate.tsx
  src/components/Main/MainBottomCarousel.tsx
  src/components/Main/MainBttomAlbum.tsx
  src/components/mypage/RecentProducts.tsx
  src/page/Detail.tsx
  src/styledComponent/styledDetail/StDetail.tsx
  src/styledComponent/styledMain/StMainCarousel.tsx
  src/styledComponent/styledMypage/StRecentProducts.ts
Labels: 💄design, ➕add

#108 리뷰 이미지 깨지는 문제 수정 / 리뷰 숫자 로직 수정
  public/img/bg1.jpg
  src/components/Detail/Product.tsx
  src/page/Detail.tsx
Labels: 🐛 fix
